### ISSUE TITLE
seal does not exit gracefully, when su is not available

### ISSUE THREAD

**Issue by radzy** [seandroid-analytics/seal#1]
$ python seal/seal.py files  
Using device {redacted}  
error: device not found  
Traceback (most recent call last):  
  File "seal/seal.py", line 829, in <module>  
    main()  
  File "seal/seal.py", line 826, in main  
    args.func(args)  
  File "seal/seal.py", line 489, in files  
    if not initialise_device(args):  
  File "seal/seal.py", line 612, in initialise_device  
    args.root_adb = check_root_adb(args.device)  
  File "seal/seal.py", line 275, in check_root_adb  
    [adb, "-s", device, "shell", "su", "-c", "id"]).strip('\r\n')  
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output  
    raise CalledProcessError(retcode, cmd, output=output)  
subprocess.CalledProcessError: Command '['adb', '-s', '{redacted}', 'shell', 'su', '-c', 'id']' returned non-zero exit status 255  
$ adb -s '{redacted}' shell su -c id  
/system/bin/sh: su: not found        

It would be nice if it would indicate that the device is not compatible, instead of the obscure python errors.

**Comment by Fbonazzi** [comment]
Thank you for the bug report. This behaviour should now be fixed in the last commit (8df9c18c5508aad6705557e3df3ae2bc6fde1dac).

Also, please note that we recommend running the tool against a debug build or rooted production device. A disclaimer has now been added to the [README](https://github.com/seandroid-analytics/seal/blob/master/README.md) and [wiki](https://github.com/seandroid-analytics/seal/wiki), and the tool will inform you if it cannot get root on the device.
