### ISSUE TITLE
polinfo is broken on android marshmallow

### ISSUE THREAD

**Issue by antojoseph** [seandroid-analytics/seal#2]
Fails with the following stack trace , because it cant parse se-linux policy v30 which is used by android marshmallow .

Using device ZX1G42778K
/tmp/tmpttj7AN/sepolicy
1081 KB/s (160013 bytes in 0.144s)
Parsing policy "/sys/fs/selinux/policy" from device...
ERROR: policydb version 30 does not match my version range 15-29
ERROR: Unable to open policy /tmp/tmpttj7AN/sepolicy.
Traceback (most recent call last):
  File "seal.py", line 838, in <module>
    main()
  File "seal.py", line 835, in main
    args.func(args)
  File "seal.py", line 361, in polinfo
    p = setup_policy(args.policy, args.device)
  File "seal.py", line 352, in setup_policy
    p = Policy(sepolicy)
  File "/home/anto/seal/seal/policy.py", line 131, in **init**
    raise IOError('Invalid policy file')
IOError: Invalid policy file

**Comment by Fbonazzi** [comment]
Thank you for taking the time to file this report.

This is a known issue - SEAL relies on setoolsv3, which supported policy versions up to 29. setoolsv3 is going to be replaced by setoolsv4 soon (it is currently in alpha).

We are going to port SEAL to setoolsv4 soon, probably in January since December is very full. There are also some other differences that we are aware of in Android 6, and that we will take care of.

**Comment by Fbonazzi** [comment]
I am currently working on porting the software to setoolsv4/Android 6. Expect a new release probably next week.

**Comment by Fbonazzi** [comment]
Fixed in [SEALv2](https://github.com/seandroid-analytics/seal/releases/tag/v2.0.0), commit 0e4a86f1e02518588dce34910f8e9125bf2b8d4d.
