### ISSUE TITLE
error on Ubuntu16.10

### ISSUE THREAD

**Issue by xinlong-song** [seandroid-analytics/seal#3]
When i use seal ,i got a error.I installed setools V4 on ubuntu.Anyone can tell ne why ?

$ python seal.py processes --permissions
Traceback (most recent call last):
  File "seal.py", line 598, in <module>
    main()
  File "seal.py", line 595, in main
    args.func(args)
  File "seal.py", line 343, in processes
    device = get_device(args.device, args.adb)
  File "seal.py", line 151, in get_device
    devices = sealib.device.Device.get_devices()
  File "/home/simon/seal/sealib/device.py", line 41, in get_devices
    [adb, "devices", "-l"]).split('\n')[1:]
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Fbonazzi** [comment]
Hi, thank you for the bug report.

I think the issue is due to the fact that you do not have `adb` in your `$PATH`, or installed at all. SEAL uses ADB to fetch information from the Android device.

If you have `adb` installed, just add it to your `$PATH`.

Otherwise, you can obtain adb in several ways: if you have Android Studio or the Android Sdk installed, you already have it most likely in `~/Android/Sdk/platform-tools`. This is the recommended way. You may also install `adb` through your distro package manager, but it may be outdated.

Actually I noticed just now that we don't specify that SEAL needs adb in the requirements. I will fix the README.

**Comment by dp140309** [comment]
Why can't download the code?  in the today ninght
yesterday i was ok !

**Comment by Fbonazzi** [comment]
> 
> 
> Why can't download the code? in the today ninght
> yesterday i was ok !

You can download the code from the [Releases](https://github.com/seandroid-analytics/seal/releases) page, or you can clone the repo.
